# Generated by Django 4.0.6 on 2022-08-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinolar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='name',
        ),
    ]
